### ISSUE TITLE
Account validation ?

### ISSUE THREAD

**Issue by MarionDaussy** [ReseauSocialStyle/ReseauSocialStyleApp#4]
https://github.com/ReseauSocialStyle/ReseauSocialStyleApp/blob/a756033072d11a5efd12b4ff34602da4fa000d68/Specs/CreationProfil.feature#L16

Should we add a step to validate account creation through a link in the mail ?

**Comment by Boussalem** [comment]
It's for security issues:

- Disabling Anonymous account Creations (Robots)
- For password Reset later
